### ISSUE TITLE
import error matplotlib.finance

### ISSUE THREAD

**Issue by Chrisebell24** [GriffinAustin/pynance#34]
After matplotlib.finance is deprecated can no longer use after a pip install

**Comment by raiavincent** [comment]
Anything on this? Think we are getting the same error.

**Comment by mrx23dot** [comment]
+1
also Yahoo finance API got cancelled doesnt it?

**Comment by philippstangl** [comment]
@Chrisebell24 In **chart.py** change `import matplotlib.finance as fplt` to `import mplfinance as fplt`.
